project_id = "irdlyshhtwzqjvymilww"

[[functions]]
name = "red-teaming-scan"
verify_jwt = true

[[functions]]
name = "scan-llm"
verify_jwt = true

[[functions]]
name = "generate-dataset"
verify_jwt = true